baseURL = "http://www.sandernaus.com/"
languageCode = "en-us"
title = "Sander Naus"
theme = "hallo-hugo"
[Author]
  name = "Sander"
[params.colors]
  background = "#EFF1F3"
  foreground = "#272727"
  hover = "#FED766"
[params]
  [[params.links]]
    icon = "linkedin"
    title = "LinkedIn"
    url = "http://www.linkedin.com/in/naussander"
  [[params.links]]
    icon = "github"
    title = "Github"
    url = "https://github.com/sandernaus"
